# -*- coding: utf-8 -*-
"""CEE412Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JOlNT6DycYpO60It9Od9vkVHljJtmNr

❗Import Pandas:
"""

import pandas as pd

"""#❗I5 (display and stats)

❗Read in and display I5:
"""

url = "/content/005es16732_loop_cloutput.csv"
I5 = pd.read_csv(url)

display(I5)

"""❗Summary stats of I5:"""

display(I5.describe())

"""# ❗SR520 (display and stats)

❗Read in and display SR 520:
"""

url2 = "/content/520es00972_loop_cloutput.csv"
SR520 = pd.read_csv(url2)

display(SR520)

"""❗Summary stats of SR520:"""

display(SR520.describe())

"""# ❗Peak Hour Volumes

❗Convert I5 to DateTime format
"""

I5['DateTime'] = pd.to_datetime(I5['DateTime'])
I5 = I5.set_index('DateTime')
print("I5 DataFrame after converting 'DateTime' to datetime and setting it as index:")
display(I5.head( ))

"""❗Find rolling 60 min volumes for each day for I5"""

I5['rolling_60min_volume'] = I5['Volume'].rolling('60min').sum()
print("I5 DataFrame after calculating rolling 60-minute volume:")
display(I5.head(24))

"""❗Find the daily peak 60 min volume for I5 and report end times"""

daily_peak_volumes = I5.loc[I5.groupby(I5.index.date)['rolling_60min_volume'].idxmax()][['rolling_60min_volume']]
daily_peak_volumes = daily_peak_volumes.rename(columns={'rolling_60min_volume': 'Peak_60min_Volume'})
daily_peak_volumes['Date'] = daily_peak_volumes.index.date
daily_peak_volumes['Peak_End_Time'] = daily_peak_volumes.index.time
daily_peak_volumes = daily_peak_volumes[['Date', 'Peak_End_Time', 'Peak_60min_Volume']]

print("Daily Peak 60-Minute Volumes and their End Times:")
display(daily_peak_volumes.head())

"""❗Repeat process for SR520"""

SR520['DateTime'] = pd.to_datetime(SR520['DateTime'])
SR520 = SR520.set_index('DateTime')
print("SR520 DataFrame after converting 'DateTime' to datetime and setting it as index:")
display(SR520.head( ))

SR520['rolling_60min_volume'] = SR520['Volume'].rolling('60min').sum()
print("SR520 DataFrame after calculating rolling 60-minute volume:")
display(SR520.head(24))

daily_peak_volumes = SR520.loc[SR520.groupby(SR520.index.date)['rolling_60min_volume'].idxmax()][['rolling_60min_volume']]
daily_peak_volumes = daily_peak_volumes.rename(columns={'rolling_60min_volume': 'Peak_60min_Volume'})
daily_peak_volumes['Date'] = daily_peak_volumes.index.date
daily_peak_volumes['Peak_End_Time'] = daily_peak_volumes.index.time
daily_peak_volumes = daily_peak_volumes[['Date', 'Peak_End_Time', 'Peak_60min_Volume']]

print("Daily Peak 60-Minute Volumes and their End Times:")
display(daily_peak_volumes.head())

"""# ❗Compare daily peak hours between I5 and SR520

❗Store I5 peak volumes in new data frame
"""

i5_daily_peak_volumes = I5.loc[I5.groupby(I5.index.date)['rolling_60min_volume'].idxmax()][['rolling_60min_volume']]
i5_daily_peak_volumes = i5_daily_peak_volumes.rename(columns={'rolling_60min_volume': 'Peak_60min_Volume'})
i5_daily_peak_volumes['Date'] = i5_daily_peak_volumes.index.date
i5_daily_peak_volumes['Peak_End_Time'] = i5_daily_peak_volumes.index.time
i5_daily_peak_volumes = i5_daily_peak_volumes[['Date', 'Peak_End_Time', 'Peak_60min_Volume']]

print("I5 Daily Peak 60-Minute Volumes and their End Times:")
display(i5_daily_peak_volumes.head())

"""❗Store SR520 peak volumes in new data frame"""

sr520_daily_peak_volumes = daily_peak_volumes

print("SR520 Daily Peak 60-Minute Volumes and their End Times:")
display(sr520_daily_peak_volumes.head())

"""❗Combine the two data frames into one for comparison"""

i5_daily_peak_volumes_renamed = i5_daily_peak_volumes.rename(columns={'Peak_60min_Volume': 'I5_Peak_60min_Volume', 'Peak_End_Time': 'I5_Peak_End_Time'})[['Date', 'I5_Peak_End_Time', 'I5_Peak_60min_Volume']]
sr520_daily_peak_volumes_renamed = sr520_daily_peak_volumes.rename(columns={'Peak_60min_Volume': 'SR520_Peak_60min_Volume', 'Peak_End_Time': 'SR520_Peak_End_Time'})[['Date', 'SR520_Peak_End_Time', 'SR520_Peak_60min_Volume']]

combined_daily_peak_volumes = pd.merge(i5_daily_peak_volumes_renamed, sr520_daily_peak_volumes_renamed, on='Date', how='outer')

print("Combined Daily Peak 60-Minute Volumes for I5 and SR520:")
display(combined_daily_peak_volumes.head())

"""❗Display PHVs and their end times for both loops"""

display(combined_daily_peak_volumes)

"""❗Plot PHVs for both I5 and SR520 on one graph"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(x='Date', y='I5_Peak_60min_Volume', data=combined_daily_peak_volumes, label='I5 Peak 60-min Volume')
sns.lineplot(x='Date', y='SR520_Peak_60min_Volume', data=combined_daily_peak_volumes, label='SR520 Peak 60-min Volume')
plt.title('Daily Peak 60-Minute Volumes: I5 vs SR520')
plt.xlabel('Date')
plt.ylabel('Peak 60-Minute Volume')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""❗Plot end times across the year for both loops"""

combined_daily_peak_volumes['I5_Peak_End_Time_Minutes'] = combined_daily_peak_volumes['I5_Peak_End_Time'].apply(lambda t: t.hour * 60 + t.minute)
combined_daily_peak_volumes['SR520_Peak_End_Time_Minutes'] = combined_daily_peak_volumes['SR520_Peak_End_Time'].apply(lambda t: t.hour * 60 + t.minute)

plt.figure(figsize=(15, 7))
sns.lineplot(x='Date', y='I5_Peak_End_Time_Minutes', data=combined_daily_peak_volumes, label='I5 Peak End Time')
sns.lineplot(x='Date', y='SR520_Peak_End_Time_Minutes', data=combined_daily_peak_volumes, label='SR520 Peak End Time')

plt.yticks(ticks=[t * 60 for t in range(24) if t % 2 == 0], labels=[f'{t:02d}:00' for t in range(24) if t % 2 == 0])

plt.title('Daily Peak 60-Minute Volume End Times: I5 vs SR520')
plt.xlabel('Date')
plt.ylabel('Peak End Time')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# ❗Time of day analysis

❗Extract time intervals from DateTime group and then calculate the average volume for each interval across the year
"""

i5_average_volume_by_time = I5.groupby(I5.index.time)['Volume'].mean().reset_index()
i5_average_volume_by_time.columns = ['Time_of_Day', 'Average_Volume']

print("Average 5-minute interval volume for I5:")
display(i5_average_volume_by_time.head())

"""❗Do the same as above but for SR520"""

sr520_average_volume_by_time = SR520.groupby(SR520.index.time)['Volume'].mean().reset_index()
sr520_average_volume_by_time.columns = ['Time_of_Day', 'Average_Volume']

print("Average 5-minute interval volume for SR520:")
display(sr520_average_volume_by_time.head())

"""❗Plot I5 and SR520 average volumes across the day"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

i5_average_volume_by_time['Time_of_Day'] = pd.to_timedelta(i5_average_volume_by_time['Time_of_Day'].astype(str))
sr520_average_volume_by_time['Time_of_Day'] = pd.to_timedelta(sr520_average_volume_by_time['Time_of_Day'].astype(str))

i5_average_volume_by_time['Time_of_Day_Seconds'] = i5_average_volume_by_time['Time_of_Day'].apply(lambda x: x.total_seconds())
sr520_average_volume_by_time['Time_of_Day_Seconds'] = sr520_average_volume_by_time['Time_of_Day'].apply(lambda x: x.total_seconds())


plt.figure(figsize=(15,7))

sns.lineplot(
    data=i5_average_volume_by_time,
    x='Time_of_Day_Seconds',
    y='Average_Volume',
    label='I-5 Average Volume'
)

sns.lineplot(
    data=sr520_average_volume_by_time,
    x='Time_of_Day_Seconds',
    y='Average_Volume',
    label='SR-520 Average Volume'
)

plt.title('Average 5-Minute Traffic Volume by Time of Day (2015)')
plt.xlabel('Time of Day')
plt.ylabel('Average Volume')

ticks_timedelta = pd.to_timedelta([f'{h:02d}:00:00' for h in range(0, 24, 2)])
tick_positions = [t.total_seconds() for t in ticks_timedelta]
tick_labels = [f'{t.components.hours:02d}:{t.components.minutes:02d}' for t in ticks_timedelta]

plt.xticks(ticks=tick_positions, labels=tick_labels, rotation=45)

plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""#❗Analyzing day of week patterns

❗Find daily volumes and find averages for each day of the week
"""

daily_volume_I5 = I5.groupby(I5.index.date)['Volume'].sum()

daily_volume_I5 = pd.DataFrame({'Volume': daily_volume_I5})
daily_volume_I5['Day_of_Week'] = pd.to_datetime(daily_volume_I5.index).day_name()

day_of_week_average_volume_I5 = (
    daily_volume_I5.groupby('Day_of_Week')['Volume']
    .mean()
    .reindex(['Monday','Tuesday','Wednesday','Thursday','Friday'])
)

"""❗Create a bar chart for average daily volumes by day of week for just I5"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(x=day_of_week_average_volume_I5.index, y=day_of_week_average_volume_I5.values, palette='viridis')
plt.title('Average Daily Volume for I5 by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Average Volume')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""❗Find daily volume averages for each week day"""

daily_volume_SR520 = SR520.groupby(SR520.index.date)['Volume'].sum()

daily_volume_SR520 = pd.DataFrame({'Volume': daily_volume_SR520})
daily_volume_SR520['Day_of_Week'] = pd.to_datetime(daily_volume_SR520.index).day_name()

day_of_week_average_volume_SR520 = (
    daily_volume_SR520.groupby('Day_of_Week')['Volume']
    .mean()
    .reindex(['Monday','Tuesday','Wednesday','Thursday','Friday'])
)

print("Average Daily Volume for SR520 by Day of the Week:")
display(day_of_week_average_volume_SR520.head())

"""❗Plot bar chart for both I5 and SR520"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

combined_day_of_week_volume = pd.DataFrame({
    'I5': day_of_week_average_volume_I5,
    'SR520': day_of_week_average_volume_SR520
})

combined_day_of_week_volume = combined_day_of_week_volume.reset_index()

combined_day_of_week_volume_melted = combined_day_of_week_volume.melt(
    id_vars=['Day_of_Week'],
    var_name='Road',
    value_name='Average_Volume'
)

day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
combined_day_of_week_volume_melted['Day_of_Week'] = pd.Categorical(
    combined_day_of_week_volume_melted['Day_of_Week'],
    categories=day_order,
    ordered=True
)

combined_day_of_week_volume_melted = combined_day_of_week_volume_melted.sort_values('Day_of_Week')

plt.figure(figsize=(12, 7))
sns.barplot(
    x='Day_of_Week',
    y='Average_Volume',
    hue='Road',
    data=combined_day_of_week_volume_melted,
    palette='viridis'
)
plt.title('Average Daily Volume by Day of the Week: I5 vs SR520')
plt.xlabel('Day of the Week')
plt.ylabel('Average Volume')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title='Road')
plt.tight_layout()
plt.show()

"""# ❗Speed Volume Relationship

❗Plot speed vs. volume for both I5 and SR520
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.scatterplot(x='Volume', y='Speed', data=I5, label='I5', alpha=0.5)
sns.scatterplot(x='Volume', y='Speed', data=SR520, label='SR520', alpha=0.5)
plt.title('Speed-Volume Relationship: I5 vs SR520')
plt.xlabel('Volume')
plt.ylabel('Speed')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""# ❗Congestion

❗Classify congestion (Speed < 40mph and Occupancy > 0.20)
"""

I5['Congested'] = (I5['Speed'] < 40) | (I5['Occupancy'] > 0.20)
SR520['Congested'] = (SR520['Speed'] < 40) | (SR520['Occupancy'] > 0.20)

"""❗Calculate daily congestion duration and average across the year"""

I5_congestion_daily = I5.groupby(I5.index.date)['Congested'].sum()
SR520_congestion_daily = SR520.groupby(SR520.index.date)['Congested'].sum()

I5_congestion_hours = I5_congestion_daily * 5 / 60
SR520_congestion_hours = SR520_congestion_daily * 5 / 60

print("Average congestion hours per weekday:")
print("I5:", I5_congestion_hours.mean())
print("SR520:", SR520_congestion_hours.mean())